services:
  adminer:
    restart: always
    image: adminer:latest
    environment:
      ADMINER_PLUGINS: "dump-json"
      ADMINER_DESIGN: "rm-soft"
    networks:
      - lungge
    depends_on:
      - postgres
    ports:
      - ${ADMINER_PORT}:8080

  postgres:
    restart: always
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - lungge
    volumes:
      - postgres_db:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432

  keycloak:
    restart: always
    image: quay.io/keycloak/keycloak:latest
    command:
      - start-dev
      - --db=postgres
      - --db-url=jdbc:postgresql://postgres:5432/keycloak
      - --db-username=${POSTGRES_USER}
      - --db-password=${POSTGRES_PASSWORD}
      - --hostname=localhost
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HOSTNAME_STRICT_BACKCHANNEL: true
      KC_HOSTNAME: localhost
    networks:
      - lungge
    depends_on:
      - postgres
    volumes:
      - keycloak_data:/opt/keycloak/data
    ports:
      - ${KEYCLOAK_PORT}:8080

volumes:
  postgres_db:
  keycloak_data:

networks:
  lungge:
