server:
  port: 8080

spring:
  application:
    name: lungge
  datasource:
    url: jdbc:postgresql://localhost:5432/lungge
    username: dev
    password: dev
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: lungge-client
            client-secret: YOUR_SECRER
            scope: openid,profile,email
            redirect-uri: http://localhost:8080/login/oauth2/code/keycloak
        provider:
          keycloak:
            issuer-uri: http://localhost:8088/realms/lungge-realm
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8088/realms/lungge-realm

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    disable-swagger-default-url: true
  api-docs:
    path: /v3/api-docs
  packages-to-scan: ua.lwjerri.lungge.controller
